### ISSUE TITLE
2020-12-29: ECGNet-AS modeling sprint

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1067]
- [ ] Hyperoptimize for binary severe vs not severe classification.
- [ ] Model progression: `P(increase in AS category from mild to moderate, or moderate to severe | two prior ECGs, and the predicted mean gradient from the first ECG ± echo measures at t0)`, excluding patients who are severe at t0.
- [ ] Regress the delta mean gradient (not just classification), e.g. `P(increase in peak gradient (mmHg) | two prior ECGs, and the predicted mean gradient from the first ECG ± echo measures at t0)`.
- [ ] Transfer learning

**Comment by StevenSong** [comment]
not a priority for now

**Comment by erikr** [comment]
Closing; this research project has been de-prioritized.
