### ISSUE TITLE
ECGNet-STS modeling sprint 1 - direct on STS data

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1070]
> Unless indicated otherwise, models are multitask, and trained on *all* (not newest) ECGs

## train directly on STS death
- [x] MLP STS features
- [x] MLP age, sex, ECG metadata
- [x] MLP age, sex, ECG metadata -- hyperoptimize
- [x] ECGNet voltage: hyperoptimize `conv_x`, `learning_rate`, and `spatial_dropout` on bootstrap 0
- [x] ECGNet voltage: train across all bootstraps on top few architectures 
- [x] ECGNet voltage, age, sex, ECG metadata
- [x] ECGNet voltage, STS features
- [x] ResNet voltage: hyperoptimize `conv_x`, `learning_rate`, and `spatial_dropout` on bootstrap 0
- [x] ResNet voltage: train across all bootstraps on top few architectures
- [x] ResNet voltage, age, sex, ECG metadata

> Dense and ConvNet are far slower to train and may not be as performant. Will omit in current sprint and discuss w/ PIs.

## ECG metadata
```
age
sex
ventricularrate
r axis
p axis
t axis
qt_interval
pr_interval
qrs_duration
afib
aflutter
vtach
vfib
svt
normal sinus rhythm
lae
rae
lbbb
rbbb
ischemia
pacemaker
atrial_paced_rhythm
lvh
rvh
mi
```

**Comment by StevenSong** [comment]
thinking about the architecture for c3po pretraining, I think we need to also train those architectures on STS alone for comparison, to see if the boost in AUC from transfer learning is due to the pretraining or simply from the different architecture - will add those to list and train `resnet`, `convnet`, `densenet`

**Comment by erikr** [comment]
Good ideas, agreed.

**Comment by StevenSong** [comment]
exciting, `sts-densenet` shared the same architecture as `transfer-c3po-densenet` but gets an AUC of 0.748 vs AUC of 0.781 - so the pretraining actually did help!!

**Comment by erikr** [comment]
if only it was 0.88 ;) but definitely a great start!

**Comment by StevenSong** [comment]
hm, `sts-resnet` achieves the same 0.78 as its transfer-learned counterpart `transfer-c3po-resnet`

**Comment by erikr** [comment]
Can you pause transfer learning models until I redo https://github.com/aguirre-lab/ml4c3/issues/1034 with the proper bootstraps?

Then we can retry.

**Comment by StevenSong** [comment]
yea, but if the architectures havent changed, will finish training those architectures directly on STS

**Comment by erikr** [comment]
Good idea

**Comment by erikr** [comment]
I updated the body text to reflect outstanding STS sprint tasks. LMK.

**Comment by erikr** [comment]
I broke up the issue into two separate issues, one for direct STS, and a second for c3po transfer learning. I'll own this one.

**Comment by StevenSong** [comment]
okay i just finished up the MLP model, will update sheets/db, auc of .75

**Comment by StevenSong** [comment]
im not sure how easy this is to own separately, its a little easier to run the direct training and transfer learning models together because the run scripts ought to be setup together

also not sure how relevant the direct training of densenet/convnet are anymore, i think the direct training and transfer learning of the c3po models should be informed by #1034

**Comment by erikr** [comment]
> im not sure how easy this is to own separately, its a little easier to run the direct training and transfer learning models together because the run scripts ought to be setup together

Makes sense. Thought we could make this big issue more granular. Can recombine.

> also not sure how relevant the direct training of densenet/convnet are anymore, i think the direct training and transfer learning of the c3po models should be informed by #1034

I thought we concluded we cannot be sure that the best model for direct training of c3po will also be the best model after fine-tuning on STS death.

e.g. DenseNet may underperform ResNet on c3po mortality, but could end up achieving the best AUC for STS after fine-tuning. 

Hence it could make sense to still train DenseNet and ConvNet.

We could prioritize ECGnet and ResNet for this sprint, present results, and ask the PIs for additional input.

Thoughts?

**Comment by erikr** [comment]
I would like to know the dimensions of the ECG latent space we concatenate tabular features to:
![Screen Shot 2021-01-07 at 11 44 12 AM](https://user-images.githubusercontent.com/1253422/103919113-aa4b7b00-50dd-11eb-80af-9534bba86d58.png)

If the dimensions of the ECG latent space are too large relative to the number of tabular features, we should increase pooling or otherwise reduce the dimensionality more.

Is there a way to do this easily, or do we have to [generate both condensed and verbose architecture diagrams](https://github.com/aguirre-lab/ml4c3/issues/1131)?

**Comment by erikr** [comment]
I finished training a variety of `mlp` (age, sex, ECG metadata) and ECGNet (voltage) models. I will combine aspects of the best models and do the other tasks now.

**Comment by erikr** [comment]
@StevenSong please review updated results in `~/dropbox/ecgnet-sts/slides/2021-01-13-sts-c3po.key`.

ResNet still training but may not include since slow and not much better.

Just need to train transfer-learned models.

Once slides updated, will share w/ PIs.

**Comment by erikr** [comment]
Hope this isn't a problem:
```
2021-01-13 21:11:13 - INFO - datasets:327 - Started 4 test workers.
2021-01-13 21:11:13 - WARNING - models:1459 - Number of x dimensions for convolutional kernel sizes (1) do not match number of convolutional layers/blocks (5), matching values to fit 5 convolutional layers/blocks.
2021-01-13 21:11:13 - WARNING - models:1459 - Number of y dimensions for convolutional kernel sizes (1) do not match number of convolutional layers/blocks (5), matching values to fit 5 convolutional layers/blocks.
2021-01-13 21:11:13 - WARNING - models:1459 - Number of z dimensions for convolutional kernel sizes (1) do not match number of convolutional layers/blocks (5), matching values to fit 5 convolutional layers/blocks.
2021-01-13 21:11:16 - WARNING - models:676 - Error loading layer dense from model: /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5. Will still try to load other layers.
2021-01-13 21:11:16 - WARNING - models:676 - Error loading layer dense_1 from model: /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5. Will still try to load other layers.
2021-01-13 21:11:16 - WARNING - models:676 - Error loading layer output_c3po_death_1_years_pre_ecg_categorical from model: /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5. Will still try to load other layers.
2021-01-13 21:11:16 - INFO - models:684 - Loaded 58 layers from /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5.
```

Script is 
```
# PREFIX=/storage/shared/sts-data
PREFIX=$HOME/dropbox/sts-data
GPU=0
BOOTSTRAP=0
./scripts/run.sh -d $GPU $PWD/ml4c3/recipes.py train \
--num_workers  4 \
--tensors      /storage/shared/ecg/mgh \
--tensors      $PREFIX/sts-mgh.csv sts \
--train_csv    $PREFIX/bootstraps-ecg/$BOOTSTRAP/train.csv \
--valid_csv    $PREFIX/bootstraps-ecg/$BOOTSTRAP/valid.csv \
--test_csv     $PREFIX/bootstraps-ecg/$BOOTSTRAP/test.csv \
--donor_layers $HOME/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5 \
--remap_layer \
    input_ecg_2500_zscore_pop_continuous input_ecg_2500_zscore_pop_60_days_pre_sts_continuous \
--input_tensors \
    ecg_2500_zscore_pop_60_days_pre_sts \
--output_tensors \
    sts_death_60_days_post_ecg \
    sts_stroke_60_days_post_ecg \
    sts_renal_failure_60_days_post_ecg \
    sts_prolonged_ventilation_60_days_post_ecg \
    sts_dsw_infection_60_days_post_ecg \
    sts_reoperation_60_days_post_ecg \
    sts_long_stay_60_days_post_ecg \
--conv_x 35 \
--conv_blocks 32 \
--conv_block_size 1 \
--conv_block_layer_order convolution normalization activation dropout \
--dense_blocks 12 24 48 96 \
--dense_block_size 3 \
--dense_block_layer_order convolution normalization activation dropout \
--pool_type max \
--pool_x 2 \
--bottleneck_type flatten_restructure \
--dense_layers 32 32 \
--activation_layer relu \
--spatial_dropout 0.25 \
--dense_dropout 0.5 \
--optimizer adam \
--learning_rate 0.0001 \
--learning_rate_patience 8 \
--learning_rate_reduction 0.5 \
--patience 24 \
--epochs 500 \
--batch_size 256 \
--output_folder $HOME/dropbox/ecgnet-sts/results/ecgnet-v011-transfer-c3po-1y/$BOOTSTRAP
```

**Comment by StevenSong** [comment]
> Hope this isn't a problem:
> 
> ```
> 2021-01-13 21:11:13 - INFO - datasets:327 - Started 4 test workers.
> 2021-01-13 21:11:13 - WARNING - models:1459 - Number of x dimensions for convolutional kernel sizes (1) do not match number of convolutional layers/blocks (5), matching values to fit 5 convolutional layers/blocks.
> 2021-01-13 21:11:13 - WARNING - models:1459 - Number of y dimensions for convolutional kernel sizes (1) do not match number of convolutional layers/blocks (5), matching values to fit 5 convolutional layers/blocks.
> 2021-01-13 21:11:13 - WARNING - models:1459 - Number of z dimensions for convolutional kernel sizes (1) do not match number of convolutional layers/blocks (5), matching values to fit 5 convolutional layers/blocks.
> 2021-01-13 21:11:16 - WARNING - models:676 - Error loading layer dense from model: /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5. Will still try to load other layers.
> 2021-01-13 21:11:16 - WARNING - models:676 - Error loading layer dense_1 from model: /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5. Will still try to load other layers.
> 2021-01-13 21:11:16 - WARNING - models:676 - Error loading layer output_c3po_death_1_years_pre_ecg_categorical from model: /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5. Will still try to load other layers.
> 2021-01-13 21:11:16 - INFO - models:684 - Loaded 58 layers from /home/erikr/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5.
> ```
> 
> Script is
> 
> ```
> # PREFIX=/storage/shared/sts-data
> PREFIX=$HOME/dropbox/sts-data
> GPU=0
> BOOTSTRAP=0
> ./scripts/run.sh -d $GPU $PWD/ml4c3/recipes.py train \
> --num_workers  4 \
> --tensors      /storage/shared/ecg/mgh \
> --tensors      $PREFIX/sts-mgh.csv sts \
> --train_csv    $PREFIX/bootstraps-ecg/$BOOTSTRAP/train.csv \
> --valid_csv    $PREFIX/bootstraps-ecg/$BOOTSTRAP/valid.csv \
> --test_csv     $PREFIX/bootstraps-ecg/$BOOTSTRAP/test.csv \
> --donor_layers $HOME/dropbox/c3po/results/1y-mortality-ecgnet/model_weights.h5 \
> --remap_layer \
>     input_ecg_2500_zscore_pop_continuous input_ecg_2500_zscore_pop_60_days_pre_sts_continuous \
> --input_tensors \
>     ecg_2500_zscore_pop_60_days_pre_sts \
> --output_tensors \
>     sts_death_60_days_post_ecg \
>     sts_stroke_60_days_post_ecg \
>     sts_renal_failure_60_days_post_ecg \
>     sts_prolonged_ventilation_60_days_post_ecg \
>     sts_dsw_infection_60_days_post_ecg \
>     sts_reoperation_60_days_post_ecg \
>     sts_long_stay_60_days_post_ecg \
> --conv_x 35 \
> --conv_blocks 32 \
> --conv_block_size 1 \
> --conv_block_layer_order convolution normalization activation dropout \
> --dense_blocks 12 24 48 96 \
> --dense_block_size 3 \
> --dense_block_layer_order convolution normalization activation dropout \
> --pool_type max \
> --pool_x 2 \
> --bottleneck_type flatten_restructure \
> --dense_layers 32 32 \
> --activation_layer relu \
> --spatial_dropout 0.25 \
> --dense_dropout 0.5 \
> --optimizer adam \
> --learning_rate 0.0001 \
> --learning_rate_patience 8 \
> --learning_rate_reduction 0.5 \
> --patience 24 \
> --epochs 500 \
> --batch_size 256 \
> --output_folder $HOME/dropbox/ecgnet-sts/results/ecgnet-v011-transfer-c3po-1y/$BOOTSTRAP
> ```

the reason the dense layers were not successfully grafted is because they differ from the architecture used to train c3po-ecgnet; the prior sota for ecgnet had `dense_layers = [16, 64]`

**Comment by erikr** [comment]
> the reason the dense layers were not successfully grafted is because they differ from the architecture used to train c3po-ecgnet; the prior sota for ecgnet had dense_layers = [16, 64]

In that case, `--dense_layers 32 32` are randomly initialized and trained from scratch?

> was there a reason for the change to 32, 32?

Yes, `ecgnet-v011` has `32, 32` and it (ever so slightly) beats `ecgnet-v001` which has `16, 64` (see results sheet).

I will re-try but with `16, 64` so the entirety of the network is transferred.
