### ISSUE TITLE
Secure visualizer app with authentication and https

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1073]
## What and why
Anyone with the URL who is logged in to the MGH network can access it.

Aaron wants this app to either be:
1. secured so it requires a username and password login and signed with SSL certificate
2. run local-only and not served over the MGH network

I think option 2 is simpler and faster.

Also, I think it is a good idea to remove the functionality to download selected data. Our pipeline doesn't support that exported data format. It is better to keep the functionality of the `visualizer` focused, and not introduce additional data formats.

**Comment by epalto** [comment]
We can implement a basic authentication method for the visualizer instance running locally similar to the jupyter one: generating a token on every visualizer run, printing it on the shell and asking for it on the browser.

For the visualizer running on Everest we could create a username and password to protect it and share them via email (or any other safe way) to whoever needs it. This username and password would be stored on Everest (I'm thinking of storing it as an environmental variable or on an encrypted file).

If this sounds good I could take care of it

**Comment by erikr** [comment]
> We can implement a basic authentication method for the visualizer instance running locally similar to the jupyter one: generating a token on every visualizer run, printing it on the shell and asking for it on the browser.

This sounds great!

> For the visualizer running on Everest we could create a username and password to protect it and share them via email (or any other safe way) to whoever needs it. This username and password would be stored on Everest (I'm thinking of storing it as an environmental variable or on an encrypted file).

That would be "nice to have", but I think our needs are met by the first solution alone. This second approach would be extra work. Is the added functionality is worthwhile? Are there reasons we should implement secure login for the app running on `everest.partners.org` instead of from a local machine?

cc @aguirre-lab/ml4c3-dev

**Comment by StevenSong** [comment]
1 username/password vs 1 token doesnt really seem like much of a difference, I think we can keep the token for the visualizer running on everest too and just be judicious about sharing the visualizer token/password

a tangible difference would be to create individual user accounts and then to actually track/log user access - this is definitely more work though unfortunately and comparing to notebooks again, is higher security than our notebooks
