### ISSUE TITLE
Remove EDW from Bedmaster tensorization

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1098]
## What and why
Cleaner organization of data and simpler code.

## Solution(s)
Refactor and simplify EDW tensorization pipeline.
Remove dependency on EDW information from Bedmaster tensorization pipeline. 

## Acceptance criteria
- Distinct `tensorize_bedmaster` recipes.
- Bedmaster data can be tensorized into distinct directory (see Discussion https://github.com/aguirre-lab/ml4c3/discussions/1095):
    ```
    /storage/shared
        /ecg             # hd5
        /edw             # hd5
        /bedmaster       # hd5
        /sts             # CSV file with tabular features
        /echo            # CSV file with tabular features
        /c3po            # CSV file with tabular features
        /aortic-stenosis # CSV file with tabular features
    ```

## Blocked by or pending

**Comment by erikr** [comment]
@RogerPallares the `CrossReferencer` class cross-references Bedmaster and EDW data:
https://github.com/aguirre-lab/ml4c3/blob/dfb50064dddbcae793c3c392fea218acb67ed3de/ingest/icu/readers.py#L1507

How can we modify the Bedmaster tensorization pipeline to be independent of EDW data? I think it may be as simple as changing the args to clarify that we cross-reference an ADT table against paths of Bedmaster files.

To be clear, I know the ADT table is from EDW. When I refer to "EDW data" I mean everything else -- medications, labs, vitals, demographics, etc.

**Comment by epalto** [comment]
Right now we can tensorize only edw or Bedmaster data by adding an emtpy folder to --edw_path or --bm_path arguments.

I suggest to use this approach instead of spliting the tensorize recipie. We can improve it doing that if the --bm_path or --edw_path is not set, the final hd5 does not incoporate data from that source. This would avoid the need of having two different recipies (tensorize_edw and tensorize_bm) while preserving the possibility to tensorize both edw and bm data on the same hd5. 

What do you think?

**Comment by epalto** [comment]
I think that despite Bedmaster and EDW data are different, there are still cases when we would want them together on the same file. For instance, we would want to use Bedmaster signals but have the static information about the patient (age, admission, etc) stored in EDW. Or we may want BM signals but also the dose of a medicine from EDW med.

I understand that there may be cases when you may really want only edw or Bedmaster data. But we can currently do that by adding an emtpy folder to --edw_path or --bm_path arguments.

I suggest to use this approach instead of spliting the tensorize recipie. We can improve it doing that if the --bm_path or --edw_path is not set, the final hd5 does not incoporate data from that source. This would avoid the need of having two different recipies (tensorize_edw and tensorize_bm) while preserving the possibility to tensorize both edw and bm data on the same hd5.

What do you think?

**Comment by RogerPallares** [comment]
The `CrossReferencer` class creates a dictionary from `xref.csv`, `adt.csv` and folders/subfolders (`mrn`/`csn`) inside the EDW directory with the following form: xref_dict = {mrn_1: csn_1: [bm_path_1, bm_path_2, ...], csn_2: [bm_path_1, bm_path_2, ...], ...,} (basically what is described here: https://github.com/aguirre-lab/ml4c3/blob/dfb50064dddbcae793c3c392fea218acb67ed3de/ingest/icu/readers.py#L1544-L1548). It is independent of EDW data, it only needs an EDW data directory.

I think we can make it fully independent from EDW (or the other way around Bedmaster) if we only add a check in the code that if `edw_dir` or `bedmaster_dir` is `None`, then it builds the dictionary without employing this directory.

**Comment by erikr** [comment]
> It is independent of EDW data, it only needs an EDW data directory.

When we separate Bedmaster and EDW tensorization:
```
/ingest
    /ecg       # organize XML files
    /edw       # pull data from EDW
    /bedmaster # pre-process alarms
/tensorize
    /ecg       # write data from XML to HD5
    /edw       # write data from CSV to HD5
    /bedmaster # write data from MAT to HD5
```

then Bedmaster tensorization should not require an EDW data directory.

> I think we can make it fully independent of EDW (or the other way around, of Bedmaster) if we only add a check in the code that if edw_dir or bedmaster_dir is None, then it builds the dictionary without employing this directory.

I'm envisioning a refactor that makes two distinct modes.

`tensorize_edw` does not require or use `--bedmaster` arg (Bedmaster directory).
`tensorize_bedmaster` does not require or use `--edw` arg (EDW directory).

However there are some overlapping pieces of code which I think we could move to the `/tensorize` directory.

**Comment by erikr** [comment]
@RogerPallares if I open a branch and outline some concepts, could you also provide input and help with some parts? I think you have more experience than me with the Bedmaster tensorization classes.

**Comment by erikr** [comment]
We need to figure out how to maintain the functionality of `assess_coverage`.

The purpose is to assess the union and intersect of MRNs and CSNs of a given cohort's Bedmaster and EDW data after tensorization.

For example, if you have 1,000 patients in a cohort, you want to know:
- `A` MRNs (and CSNs) have EDW data
- `B` MRNs (and CSNs) have Bedmaster data
- `C` MRNs (and CSNs) have both EDW and Bedmaster data
- `D` MRNs (and CSNs) have no EDW or Bedmaster data

@raimonpv I think you wrote `assess_coverage`; can you confirm if above describes desired functionality? Anything missing?

@StevenSong I think this functionality is mostly handled by `explore`. Should we deprecate `assess_coverage` in favor of `explore`? One advantage of shifting to `explore` is the ability to use Tensor Maps to focus the assessment on specific data of interest, e.g.
- `A` MRNs (and CSNs) have lab tests in EDW
- `B` MRNs (and CSNs) have pulmonary arterial pressure in Bedmaster
- `C` MRNs (and CSNs) have both labs from EDW and PA pressures in Bedmaster
- `D` MRNs (and CSNs) have none of the above

**Comment by raimonpv** [comment]
PR #1166 will enable this feature. Nevertheless, the code should be revised and cleaned to create two different functionalities.

**Comment by raimonpv** [comment]
@erikr assess_coverage does exactly what you described. I don't think that its functionality will be affected when separating EDW from Bedmaster, if it does, few changes are needed. Furthermore, as you point out, with adequate tmaps you could obtain similar results, the unique advantage of this code is that also assess the coverage from adt table (some patients might not be downloaded from EDW)

**Comment by erikr** [comment]
Thanks for clarifying.

> Furthermore, as you point out, with adequate tmaps you could obtain similar results, the unique advantage of this code is that also assess the coverage from adt table (some patients might not be downloaded from EDW)

Perhaps we should deprecate `assess_coverage` and add functionality for `explore` to also be able to assess entries from the ADT table.

Or, we simplify `assess_coverage` (users use `explore` for above functionality) and simplify it to `assess_coverage_from_adt_table`.
