### ISSUE TITLE
Dataset parses directory with MRN/CSN/type.csv files, not only one data.csv

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1111]
## What and why
Enables:
```
--tensors /storage/shared/ecg \
--tensors /media/ml4c3/edw \
```

**Comment by StevenSong** [comment]
The implementation I have in mind is as follows:

```
- dataset iterates over MRNs
  - if MRN exists at `/media/ml4c3/edw`
    - for each encounter
      - for each CSV
        - read CSV and add to PatientData object
```

but most of the time, we just want a few measurements from e.g. the flowsheet

needing to read entire CSVs for each patient just to get those few measurements will probably end up being slower than creating an HD5 of EDW data that makes each measurement directly addressable and doesnt require reading extraneous data

the benefit of not tensorizing tabular data really comes from being able to read a table once and store it in memory on a cohort level - things like the STS, Echo, or ICI data

**Comment by erikr** [comment]
> The implementation I have in mind is as follows:
> 
> ```
> - dataset iterates over MRNs
>   - if MRN exists at `/media/ml4c3/edw`
>     - for each encounter
>       - for each CSV
>         - read CSV and add to PatientData object
> ```
> 
> but most of the time, we just want a few measurements from e.g. the flowsheet
> 
> needing to read entire CSVs for each patient just to get those few measurements will probably end up being much much slower than creating an HD5 of EDW data that makes each measurement directly addressable and doesnt require reading extraneous data

Good point. I also think it is likely that reading many CSVs to get a few measurements will be slower than working with HD5 files. However, a more precise estimate of the speeds will help us understand the tradeoff of tensorizing CSV to EDW, which informs our decision on how we write and read these data.

The script [`benchmark_csv_hd5_speed.py`](https://github.com/aguirre-lab/ml4c3/blob/master/scripts/benchmark_csv_hd5_speed.py) is a starting point. Could you look at the script and see if there is a way to more closely simulate the scenario we're describing above?

We also should not confine ourselves to CSV vs HD5. Perhaps there is another representation of EDW data -- such as a Parquet columnar table -- that is highly performant and compressible, that we should investigate and implement.

> the benefit of not tensorizing tabular data really comes from being able to read a table once and store it in memory on a cohort level - things like the STS, Echo, or ICI data

agreed

**Comment by StevenSong** [comment]
additionally thinking about the tmap implementation (#1110), the first step of those will probably be pandas operations:

```python
df = data['edw'][csn]['flowsheet']
value = df[df['DisplayNM'] == measurement]
```

this is a fairly expensive operation as a flowsheet is a very large table - while this operation would occur in memory, i wonder if it would be slower and less memory efficient than a direct hd5 read:

```python
value = data['edw/csn/flowsheet/measurement']
```

this might end up being an easier benchmarking point, if this test fails, there's for sure no benefit to reading the massive amount of CSV files mentioned in the last comment

**Comment by StevenSong** [comment]
same patient encounter as csv and hd5, after data is loaded, pandas operation is slower:
![image](https://user-images.githubusercontent.com/26208374/105516443-e2d58200-5ca3-11eb-8c65-a09341102ee7.png)

**Comment by StevenSong** [comment]
even opening the csv vs the hd5:
![image](https://user-images.githubusercontent.com/26208374/105517470-15cc4580-5ca5-11eb-93bc-0742ca104edb.png)

**Comment by StevenSong** [comment]
going to close this, the infra to tensorize and work with EDW data is already in place and this would make it slower, can reopen if there are other ideas on why this is better

**Comment by erikr** [comment]
Thanks, agree with your assessment -- nice work.

**Comment by erikr** [comment]
Also tagging @aguirre-lab/ml4c3-dev so everyone aware of plan to keep EDW data in `hd5` format.
