### ISSUE TITLE
test_cross_referencer fails on master

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1116]
## Error message or warning
```
>       assert cross_referencer.get_xref_files(mrns=["456"]) == expected_dict2
E       AssertionError: assert {} == {'456': {'980...3_1_v4.mat']}}
E         Right contains 1 more item:
E         {'456': {'980': ['/Users/erikr/ml4c3/tests/icu_ingest/data/bedmaster/file3-123_1_v4.mat']}}
E         Use -v to get the full diff

ml4c3/tests/icu_ingest/test_cross_referencer.py:51: AssertionError
```

## Expected behavior
No tests fail

## Possible solution
Fix tests

## Steps to reproduce
```
./scripts/run.sh -t $PWD/tests -m '"not slow"'
```

**Comment by epalto** [comment]
This issue comes from the new docker image. When generating a new one with `docker/build.sh`, even with no modifications, the tests don't pass

**Comment by erikr** [comment]
A package must have updated that changes the behavior of a function or class that consequently causes a test to fail.
