### ISSUE TITLE
Assess ResNet performance on varying amounts of c3po data

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1118]
## Question or modeling task
Train ResNet model on c3po mortality with varying amounts of data.
This lets us decide if we can train models on a representative subset of data without substantially harming performance.
If the answer to above is "yes", then we can explore our model space faster.

## Blocked by or pending
https://github.com/aguirre-lab/ml4c3/issues/1117

**Comment by erikr** [comment]
If we had infinite compute I'd want to compare all vs newest ECG only

**Comment by StevenSong** [comment]
#1117 done
