### ISSUE TITLE
Train ECGNet to predict STS death using all pre-op (30d window) ECGs

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1119]
## Question or modeling task
Instead of newest, train on all ECGs in pre-op window.
Each ECG gets the same label.

## Blocked by or pending

**Comment by StevenSong** [comment]
new AUC of 0.779!! db/sheets updated, `use-all-ecgs`

**Comment by erikr** [comment]
I'm stoked about this and going to train a few random variants.

**Comment by erikr** [comment]
New random weights, same exact settings as your `v001`, got 0.783 hah.

None of the variants I tried beat it, so I'm repeating the same five but with batch normalization. Will also try a few more ideas tomorrow AM.

**Comment by erikr** [comment]
Batch norm reduces performance. Updating slides `~/dropbox/ecgnet-sts/slides/2021-01-06-sts-c3po.key`.

Can you please add info about training STS on all ECGs? The relevant slide has a sticky note with comments for you. Thanks!
