### ISSUE TITLE
Assess number of ECGs within STS 30d window across bootstraps and splits

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1120]
## Question or modeling task
We are considering training on all ECGs instead of newest.
We stratify train, val, test splits by MRN.
Hence, training split in bootstrap 0 may have a different number of Eggs than training split in bootstrap 1.
It may not be ideal if the number of ECGs varies too much across bootstraps.
Need to quantify this.

**Comment by StevenSong** [comment]
the datasheet has some other columns of actual counts, its in the STS results google sheet, sheet titled `bootstrap-coverage`

**Comment by erikr** [comment]
2% (absolute) spread is not bad, but could be lower. Oh well.
