### ISSUE TITLE
Pull hemodynamics and fick measurements from EDW

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1123]
## Question or modeling task
- identify where and how these data are stored in EDW
- update EDW query in pipeline to get the data

## Data of interest
```
cvp (central venous pressure)
pap (pulmonary artery pressure)
CO (cardiac output)
SVR (stroke volume ratio)
SV (stroke volume)
thermodilution CO (fick cardiac output)
MVO2 (mixed venous oxygen)
```

**Comment by StevenSong** [comment]
these are in flowsheet and we pull everything in the flowsheets already
