### ISSUE TITLE
Any Updates on Issue 103 and Issue 1048

### ISSUE THREAD

**Issue by contactadityag** [aguirre-lab/ml4c3#1134]
## Question or modeling task
Hi @erikr, Do you have any updates regarding which columns in the xref.csv sample that you shared with us: https://www.dropbox.com/s/7k88uonxq82zobu/xref.csv?dl=0 are required: https://github.com/aguirre-lab/ml4c3/issues/1048 and which columns are optional. Also if you have any details regarding the differences between room_bed and BedLabelNM column that will be really helpful. Also it will be really helpful if there can be a one line description of what information these columns are trying to capture: https://github.com/aguirre-lab/ml4c3-wiki/issues/103

**Comment by erikr** [comment]
Hi Aditya, since these questions follow up on existing Discussions and Issues, I'll reply in the appropriate place. Closing. Thanks.
