### ISSUE TITLE
Modularize and separate evaluation from plotting code

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1138]
## What and why
`evaluate_predictions` is in `plots.py`. This large function both evaluates model performance on labels and plots performance metrics.

## Solution(s)
Separate functions to evaluate model performance on labels from functions that plot performance metrics.
The former family of functions should return objects that can be used as input for the second family of functions.
The former family of functions should live in `evaluations.py`, whereas the former family of functions should live in `plots.py`.

**Comment by StevenSong** [comment]
this seems like just moving the function `evaluate_predictions` to `evaluations.py` as the actual plotting functions are distinct methods in `plots.py`
