### ISSUE TITLE
EDW pull duplicates rows when a patient was in many departments

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1142]
## Error message or warning
I've only checked flowsheets but it might be in other tables as well.

The [flowsheet query](https://github.com/aguirre-lab/ml4c3/blob/master/ingest/edw/queries-pipeline/flowsheet.sql) joins the ADT table and the flowsheet table on PatientID [EDW Atlas](https://enterpriseanalytics.partners.org/Atlas/View/Columns/Epic?viewId=2211)

A patient who was in multiple departments will have each flowsheet repeated for each department they were in.

For example, a pt with ADT:
```
ADT
---
Ellison 11
Blake 8
Surgery
```

and flowsheet:
```
flowsheet
---
Pulse 60 (from stay in Blake 8)
```

will result in the following csv:
```
Ellison 11 | Pulse 60
Blake 8    | Pulse 60
Surgery    | Pulse 60
```

## Expected behavior
The resulting csv we expect is:
```
Ellison 11 |
Blake 8    | Pulse 60
Surgery    |
```
 

## Possible solution
We want to not duplicate rows and preserve the department each measurement was taken in. This requires knowing the transfer in/out time of each department and the time each measurement was taken. We have all this information. The only difficulty is coming up with the SQL to achieve this join.

**Comment by StevenSong** [comment]
just so we dont have to repull EDW data which is a pain, we can put together a script to trawl through our existing EDW data and cleanup rows for which the measurement was not actually taken in the department

but we should still engineer the pipeline to pull the data correctly for future pulls

**Comment by RogerPallares** [comment]
Great you found the source of this error! Tensorize pipeline removes the duplicates, we were already aware of this, but never knew why this happened.

**Comment by StevenSong** [comment]
oh i see, that's great - an important step to not gloss over for #1100 perhaps and a cautionary step to not work directly with the EDW csv without some cleaning

**Comment by erikr** [comment]
@StevenSong did you mean to reference https://github.com/aguirre-lab/ml4c3/issues/1098? #1100 is a half-hearted PR that never took flight.

**Comment by StevenSong** [comment]
ah yes, whatever issues we're using to use EDW alone, perhaps ill add it to that milestone

**Comment by StevenSong** [comment]
@RogerPallares do u know if other tables other than flowsheet are affected?

**Comment by RogerPallares** [comment]
As far as I know only flowsheets are affected, let me double check, but I'm pretty sure that only flowsheets.

**Comment by RogerPallares** [comment]
Just checked, only flowsheets have repeated rows.
