### ISSUE TITLE
Delete slow tests for model factory

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1159]
## Question or modeling task
slow tests are for model factory, but has not been updated to reflect major revisions in model factory

## Blocked by or pending

**Comment by raimonpv** [comment]
should I delete the tests or just that by default the `not slow` version is run?

**Comment by StevenSong** [comment]
delete the tests, i'm 99% sure they dont work anymore anyways

**Comment by erikr** [comment]
Raimon thanks for proposing. Good idea.
