### ISSUE TITLE
Parallelize sklearn models

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1170]
## What and why

sklearn models have a parameter `n_jobs` to their `fit` functions - setting this parallelizes the model fitting and can speed up model training

discussion on why this is feasible and safe in the context of our parallelized data loading pipeline: #1167 

## Solution(s)

set `n_jobs = num_workers` here:
https://github.com/aguirre-lab/ml4c3/blob/b546ab6e6bcd08107ef6dd13a213613749a98ee9/ml4c3/models.py#L201

## Acceptance criteria

sklearn model training is parallelized

**Comment by erikr** [comment]
The fact this was so fast to set up is a testament to sklearn doing things well and also our codebase for being organized and granular 😀

**Comment by erikr** [comment]
Thanks for making the issue!
