### ISSUE TITLE
isort and black fight over space between import statement and comment in next line

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1171]
## Error message or warning

Given
https://github.com/aguirre-lab/ml4c3/blob/d90a04914307fe120c4bb009bd131395f42c9953/ml4c3/recipes.py#L126-L133

Running `isort` removes the newline between the import statement and the comment:
```python
    from ml4c3.datasets import (  # isort: skip
        get_split_stats,
        get_verbose_stats_string,
        train_valid_test_datasets,
    )
    # Create datasets
    datasets, stats, cleanups = train_valid_test_datasets(
```

Running `black` reinserts the removed newline.

As a consequence, the code cannot satisfy both `black` and `isort` pre-commit hooks.

## Expected behavior
Newline is respected and conserved, and both `isort` and `black` find nothing to cry about:
```python
    from ml4c3.datasets import (  # isort: skip
        get_split_stats,
        get_verbose_stats_string,
        train_valid_test_datasets,
    )

    # Create datasets
    datasets, stats, cleanups = train_valid_test_datasets(
```

## Possible solution
Our `isort` settings should be compatible with `black` https://github.com/aguirre-lab/ml4c3/blob/d90a04914307fe120c4bb009bd131395f42c9953/pyproject.toml#L5

but clearly it is not working.

Long-term fix will come from `black` and `isort` contributors.

For us, perhaps we find a setting in our `pyproject.toml` that solves the problem.

`black` docs on isort compatibility https://black.readthedocs.io/en/stable/compatible_configs.html#isort
`isort ` docs on black compatibility https://github.com/psf/black/blob/master/docs/compatible_configs.md#why-those-options-above

## Steps to reproduce
1. Run `pre-commit autoupdate` to update all pre-commit hooks to latest versions.
1. Run `pre-commit run isort --all-files`.
1. Run `pre-commit run black --all-files`.

**Comment by erikr** [comment]
Hey @epalto, I don't think `pre-commit` hooks have this problem any more on `master`. What do you think?

**Comment by erikr** [comment]
@epalto Any progress figuring this one out? Issue is still occurring for me on `master`.

**Comment by epalto** [comment]
Sorry, my previous issue took longer than expected but I can take a look at it now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by erikr** [comment]
No problem! Was just curious.

**Comment by epalto** [comment]
Found a workaround by making isort ignore whitspaces, so that all the whitespaces are managed by Black. Pre-commit should pass with the proposed  `pyproject.toml` on #1186
