### ISSUE TITLE
c3po-ecgnet-v001-5y-voltage-age-sex AUC is 0.50

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1175]
The AUC for [`~/dropbox/c3po/results/c3po-ecgnet-v001-5y-voltage-age-sex`](https://www.dropbox.com/sh/3dcdctbhxy7efbu/AABF9deykjeMJOwhhZQ1l1ILa?dl=0) is 0.5. This is strange when the same model and data, but only training on voltage, achieves an AUC of 0.787.

**Comment by erikr** [comment]
@StevenSong I realize this is challenging to debug but next week could you please take a look and see if anything obvious is wrong in the logs? If not, we'll probably archive these results and move forward (see https://github.com/aguirre-lab/ml4c3/issues/1195) per Collin's direction.

Also note c3po tasks are to fill downtime; work that gets STS closer to publication is the priority.

**Comment by StevenSong** [comment]
I didn't see anything wrong in the log, perhaps rerun?

**Comment by erikr** [comment]
Rerunning on GPU 0 on Anduril.
