### ISSUE TITLE
Make `assess_coverage.py` functional for both EDW and Bedmaster.

### ISSUE THREAD

**Issue by raimonpv** [aguirre-lab/ml4c3#1177]
## What and why
`assess_coverage.py` is a recipes mode that assess the coverage between EDW, Bedmaster, and HD5 files in raw format. With the recent changes in the repo it won't work anymore. 

## Solution(s)
Modify the current code, create a new one or develop tmaps that will allow assessing the coverage for the desired cohorts using tmaps.

**Comment by raimonpv** [comment]
I am not sure if this code is useful anymore if EDW is separated from Bedmaster. The purpose was to assess coverage between adt, xref and hd5 files. I think that we can obtain similar results using explore. Do you think that we can delete it @erikr? If so, let me know that I'll open a PR deleting this recipe

**Comment by erikr** [comment]
@raimonpv I agree!

We could wait to delete it in the same PR as one that ensures the same functionality is in the repo, e.g. update to tmaps and `explore`.

 But actually I think this is a good decision for you to think about and make. So if you are confident that we can delete it, please open the PR. We can always recover it thanks to version control.
