### ISSUE TITLE
Make clustering finder general to any time in hospitalization

### ISSUE THREAD

**Issue by epalto** [aguirre-lab/ml4c3#1209]
## What and why
Right now, clustering-find and extract only gets signals on the first BLK08 admission of a patient. If would be interesting to let the user decide which part of the hospitalization is to be used. For instance, the user may want to explore the Elison 09 part or the hospitalization.

## Solution(s)
 It could be generalized with an extra argument like `--movement` with which you could specify the moment of the patient hospitalization from which you could take the signal. For instance, `--movement BLK08` would extract only the part of the signal of BLK08 but  `--movement ELL09` would extract only Elison 09. If  no `--movement` is set or  `--movement all`, then all the signal would be considered.

## Acceptance criteria
Finder accepts the `--movement` parameter

**Comment by erikr** [comment]
If the value of the argument reflects the location or department, perhaps a clearer argument name is `--location` or `--department`?
