### ISSUE TITLE
Analyze cluster mean trajectories on different timelapses

### ISSUE THREAD

**Issue by epalto** [aguirre-lab/ml4c3#1216]
## Question or modeling task
Cluster a cohort based on the first 2h hours of data and get the average trajectory for each signal on each cluster. Redo clustering with 4h and get the same trajectories. Repeat the process with 6h, 8h, and so on. See if there is a relationship between trajectories on shorter and longer trajectories, i.e: trajectories clustering with 2h of data are similar to the first 2h of the trajectories clustering with 6h of data, and so on

**Comment by erikr** [comment]
I understand your question above is "What is the relationship between length of data vs cluster distinctiveness?".

On a different note, features from a time series are sometimes predictive when computed from a different time scale.

A method of assessing varying time scales is to coarse-grain the time series: http://physionet.incor.usp.br/physiotools/mse/tutorial/node1.html

Given a time series of `n` samples, you coarse grain over `t` time scales.

For the `t'th` time scale, average `t` adjacent samples together into one new sample:
![image](https://user-images.githubusercontent.com/1253422/105798722-cfa30a80-5f60-11eb-9e6d-240c95f5060d.png)

At time scale 1, the time series is unchanged from the original. Features are computed from this time series and appended to an array.

At time scale 2, you average samples `[0, 1]` into the new sample 1, `[2, 3]` into the new sample 2, etc. Features are computed from this new time series and appended to an array.

Rows are time scales and columns are features:

```
                 0     1   ...     n
time-scale-1  0.66  0.25  0.46  0.01
time-scale-2  0.84  0.44  0.30  0.50
...           0.05  0.73  0.37  0.26
time-scale-t  0.98  0.13  0.38  0.98
```
This is an array for one patient; it can be flattened so your array is organized via one row per patient.

You can then use the array as input to a clustering algorithm.

**Comment by epalto** [comment]
That's great! I will implement it! Thank you!
