### ISSUE TITLE
patient_csv_to_set: error trying to cast a pd.Series of MRN strings into ints

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1222]
## Error message or warning
`patient_csv_to_set` attempts to cast a `pd.Series` of MRNs into ints.

If the primitive type of the MRNs, imported from a CSV, is string, e.g.
```
1234.0
```
then the following error is thrown:

```
df['mrn'].dropna().astype(int)
*** ValueError: invalid literal for int() with base 10: '1234.0'
```

## Expected behavior
MRNs are parsed into ints without an error.

## Possible solution
To ingest strings, floats, or ints, first cast to float and then to int.
This is more flexible than assuming the CSV type only contains ints or floats, and does not slow down the pipeline.

## Steps to reproduce
Error discovered when trying to train a c3po mortality prediction model on a freshly regenerated `c3po-formatted.csv` file; apparently [`c3po-preprocess-and-fix-bwh-mrns.ipynb`](https://github.com/aguirre-lab/ml4c3/blob/master/notebooks/c3po/c3po-preprocess-and-fix-bwh-mrns.ipynb) exported MRNs as strings instead of ints or floats.
```
PREFIX_DATA=$HOME/dropbox
# PREFIX_DATA=/storage/shared
PREFIX_RESULTS=$HOME/dropbox/c3po/results
# PREFIX_RESULTS=$HOME

./scripts/run.sh -d 0 $PWD/ml4c3/recipes.py train \
--num_workers 10 \
--cache_off \
--tensors   /storage/shared/ecg \
--tensors   $PREFIX_DATA/c3po/data/c3po-formatted-mrn.csv c3po \
--train_csv $PREFIX_DATA/c3po/data/train.csv \
--valid_csv $PREFIX_DATA/c3po/data/valid.csv \
--test_csv  $PREFIX_DATA/c3po/data/test.csv \
--input_tensors \
    ecg_2500_zscore_pop \
    ecg_age \
    ecg_sex \
--output_tensors \
    c3po_death_5_years_post_ecg \
--conv_x 35 \
--conv_blocks 32 \
--conv_block_size 1 \
--conv_block_layer_order convolution normalization activation dropout \
--dense_blocks 12 24 48 96 \
--dense_block_size 3 \
--dense_block_layer_order convolution normalization activation dropout \
--pool_type max \
--pool_x 2 \
--bottleneck_type flatten_restructure \
--dense_layers 128 64 32 16 8 \
--activation_layer relu \
--spatial_dropout 0.2 \
--dense_dropout 0.5 \
--optimizer adam \
--learning_rate 0.0001 \
--learning_rate_patience 8 \
--learning_rate_reduction 0.5 \
--patience 24 \
--epochs 500 \
--batch_size 256 \
--output_folder $PREFIX_RESULTS/c3po-ecgnet-v001-5y-voltage-age-sex
```

**Comment by StevenSong** [comment]
ahh, this is why this section existed before https://github.com/aguirre-lab/ml4c3/blame/46b97e53bdfe417993d325ca5267c811af5c3db8/ml4c3/datasets.py#L838

**Comment by erikr** [comment]
Yeah, it felt familiar. But now we're returning `Set(int)` instead of `Set(str)`.
