### ISSUE TITLE
Tensorize alarms via independent bedmaster tensorization pipeline

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1232]
## What and why
Alarms data are preprocessed from a gigantic CSV into a smaller CSV, but it still is not tensorized.
This data is important as it forms (noisy) labels, outcomes, etc.

## Solution(s)
Update Bedmaster tensorization pipeline to also tensorize alarms.

## Acceptance criteria
Bedmaster files include alarms data.

**Comment by raimonpv** [comment]
clarification: alarms are already tensorized in the current pipeline ('/ingest/icu'), but not in the independent bedmaster pipeline ('/tensorize/bedmaster')

**Comment by erikr** [comment]
Ah, thanks for clarifying. This makes more sense.
