### ISSUE TITLE
Delete repo and re-clone from remote

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1245]
To ensure our commit history is cleaned appropriately, please indicate here that you have deleted your local repo and re-cloned from remote (e.g. do a fresh `git clone git@github.com:aguirre-lab/ml4c3.git`):

- [x] @epalto 
- [x] @StevenSong 
- [x] @erikr 
- [x] @RogerPallares 
- [x] @raimonpv 
- [x] @RidwanAlam 
- [x] @matt-cdac 

Eric, please also follow up with @contactadityag and @matt-cdac to ensure they either have not pulled recent commits that introduced sensitive data, or do above steps too.

Thanks all!

**Comment by RidwanAlam** [comment]
I am still waiting for the tensorization to finish; will do the clone as soon as that's done.

**Comment by matt-cdac** [comment]
Confirming I've deleted my copy of the repo and will reclone

**Comment by contactadityag** [comment]
@erikr, I had cloned the repo recently but I have deleted all my copies and will reclone it again when I need to use it.

**Comment by epalto** [comment]
Just a heads up, you will need to run `pre-commit install` again to reinstall the pre-commit hooks

**Comment by erikr** [comment]
> Just a reminder, you will need to run `pre-commit install` again to reinstall the pre-commit hooks

can also do `make setup`!
