### ISSUE TITLE
Case mismatch of dataframe column in cross referencer

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1261]
## Error message or warning
Cross referencer expects lower case `"path"` in xref file
https://github.com/aguirre-lab/ml4c3/blob/27e798e2b788c91abe9cb5a7ca44f78f90cccb8f/tensorize/bedmaster/readers.py#L742

whereas patient bedmaster matcher now saves it as upper case `"Path"`
https://github.com/aguirre-lab/ml4c3/blob/27e798e2b788c91abe9cb5a7ca44f78f90cccb8f/tensorize/bedmaster/match_patient_bedmaster.py#L143

## Expected behavior
not that

## Possible solution
change case in cross referencer

**Comment by StevenSong** [comment]
It seems like this also needs to change in `tensorizer`, `pre_tensorize_explorations`, and another line in `readers`

links:
- tensorizer: https://github.com/aguirre-lab/ml4c3/blob/27e798e2b788c91abe9cb5a7ca44f78f90cccb8f/tensorize/bedmaster/tensorizer.py#L227
- pre_tensorize_explore: https://github.com/aguirre-lab/ml4c3/blob/27e798e2b788c91abe9cb5a7ca44f78f90cccb8f/ingest/icu/pre_tensorize_explorations.py#L220
- readers: https://github.com/aguirre-lab/ml4c3/blob/27e798e2b788c91abe9cb5a7ca44f78f90cccb8f/tensorize/bedmaster/readers.py#L802

@raimonpv could you confirm these are all the places?

**Comment by erikr** [comment]
Related https://github.com/aguirre-lab/ml4c3/issues/1229

**Comment by raimonpv** [comment]
my bad sorry. Also here:
https://github.com/aguirre-lab/ml4c3/blob/27e798e2b788c91abe9cb5a7ca44f78f90cccb8f/tensorize/bedmaster/readers.py#L742

I think that there shouldn't be any other place. (I've checked using pycharm)
