### ISSUE TITLE
Rename `.mat` files to include the start and end time of the individual bundle

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1266]
## Question or modeling task
instead of `<unit>_<room>-<start_time>_<bundle>_v4.mat`, reformat to `<unit>_<room>-<start_time>-<end_time>_<bundle>_v4.mat`

this would make #1265 easier

**Comment by StevenSong** [comment]
@contactadityag @matt-cdac how possible is this?

**Comment by erikr** [comment]
For reference, please see https://github.com/aguirre-lab/ml4c3/issues/1258 (which I am sure is prominent among your GitHub notifications)

**Comment by erikr** [comment]
@StevenSong and I spoke with Brandon. Not feasible for CDAC to rename all `.mat` files. Closing.

**Comment by matt-cdac** [comment]
@erikr & @StevenSong, couldn't we add some logic to incorporate the starting timestamp of the 'next' bundle for the given location?

Also, given that each _v4.mat file is partitioned on 1000 minutes of data with the exception of the last file in the bundle, couldn't we run some quick calculation to get an estimate of the final timestamp, and only open that file to check the timestamp if necessary? That might look something like returning the name of the last _v4.mat file in the bundle and checking its last timestamp if we are looking for a timestamp within 1000 minutes of <bundle start time> x <number of _v4.mat files in bundle> ?

**Comment by StevenSong** [comment]
> @erikr & @StevenSong, couldn't we add some logic to incorporate the starting timestamp of the 'next' bundle for the given location?
> 
> Also, given that each _v4.mat file is partitioned on 1000 minutes of data with the exception of the last file in the bundle, couldn't we run some quick calculation to get an estimate of the final timestamp, and only open that file to check the timestamp if necessary? That might look something like returning the name of the last _v4.mat file in the bundle and checking its last timestamp if we are looking for a timestamp within 1000 minutes of x ?

the fact that each bundle is 1000 minutes is really helpful actually, that ought to be enough to get a rough estimate of start/end times for each bundle, coupled with the next file for a given bed

**Comment by StevenSong** [comment]
@matt-cdac is that 1000 minutes of non-contiguous data? the difference being if there's a bundle with a time jump in it, does the jump count towards the 1000 minutes?

**Comment by erikr** [comment]
so if you have an encounter matched to three `.mat` files:
```
<unit>_<room>-<start_time>_1_v4.mat
<unit>_<room>-<start_time>_2_v4.mat
<unit>_<room>-<start_time>_3_v4.mat
```
We assume the first `.mat` file only contains data for the patient associated with that time and bed.

Where is `t_start` from? the first `.mat` file?

Regardless, say we know and trust `t_start`. That means `t_end <= t_start + 1000 + 1000 + x`, where `x` is the number of minutes in the last `.mat` file; `1000 >= x >= 0`.

How do we use that to determine if it is necessary to open the `.mat` file to check the timestamp?

**Comment by StevenSong** [comment]
going back to what @RidwanAlam said in slack, I think actually perhaps its time to stop relying on assumptions and to just get the actual data - I remembered a thing @epalto had said where each bundle actually includes some overlap with the prior bundle and so its 1000 minutes of data for the first bundle, but then 1100 for those after the first, until the last bundle which is shorter. But even then, its not exactly 1000 or 1100 minutes, there's some variance which is probably due to how the sampling rates of waveforms line up with those delimiters - I'm going to go back to engineering a more robust solution

**Comment by matt-cdac** [comment]
@StevenSong to answer your earlier question, I'm not 100% sure about contiguous data but I would guess the 1000 minutes is just the end time stamp of the .mat file partition and doesn't necessarily mean the file itself has 1000 minutes of data if there were jumps forward.

regarding the 1000/1100 minutes piece, I read this in the wiki:
https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-raw-data#structure

**Comment by erikr** [comment]
@StevenSong I agree to not rely on assumptions. We have to iterate over many files anyways, so we might as well be precise and correct with time stamps, instead of estimate or calculate. It will be slow but ideally only done once.

**Comment by erikr** [comment]
> regarding the 1000/1100 minutes piece, I read this in the wiki:
> https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-raw-data#structure

Thanks @matt-cdac! @wolfgang-ganglberger can you confirm if the section in the wiki about 1000/1100 minutes is correct? Is it correct most of the time, but not guaranteed? We may need to update the wiki page.

**Comment by StevenSong** [comment]
for reference, the 1100 ± some amount is based on these files and checking channel 8:
![image](https://user-images.githubusercontent.com/26208374/106294096-bcbc5e80-621c-11eb-80ae-251b461dbbdd.png)
(t_start for t3 and t4 are index 1 b/c index 0 is nan)
