### ISSUE TITLE
pre-commit hooks check committed code for PHI

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1270]
## What and why
It can be difficult to ensure you do not commit PHI, and we should automate everything!

## Solution(s)
`pre-commit` hook?

**Comment by StevenSong** [comment]
just following up on slack discussion, quick search of our codebase shows that there's only a few instances of numbers > 4 digits long - 4 digits is the smallest real MRN i've seen so perhaps we should use that as the threshold and build some mechanism to ignore the very few examples of 4 digit numbers in our code
