### ISSUE TITLE
Stop Warnings related to edw data to appear while tensorizing bedmaster data.

### ISSUE THREAD

**Issue by contactadityag** [aguirre-lab/ml4c3#1274]
## What and why
When using the tensorize_icu_no_edw_pull command we do not need to display any warnings related to edw data. This will help us in decoupling the edw tensorization from the bedmaster tensorization. 

## Solution(s)
Change the code in https://github.com/aguirre-lab/ml4c3/blob/master/ingest/icu/utils.py and https://github.com/aguirre-lab/ml4c3/blob/master/ingest/icu/readers.py to remove the warning in case of tensorize_icu_no_edw_pull command.

## Acceptance criteria
The warnings disappear when you tensorize only bedmaster data.

**Comment by raimonpv** [comment]
@contactadityag are these warnings still showing up when you tensorize or we can close the issue?

**Comment by contactadityag** [comment]
@raimonpv, I have been using the tensorize_bedmaster option and not getting any warnings. What is the difference between doing tensorization using tensorize_icu_no_edw_pull and doing tensorization using tensorize_bedmaster?

**Comment by raimonpv** [comment]
the difference is that `tensorize_icu_no_edw_pull` was developed to tensorize both EDW and Bedmaster data while `tensorize_bedmaster` is just to tensorize bedmaster data. 

As this is not an issue anymore I'll close.
