### ISSUE TITLE
bedmaster_index saves start and end times as integers

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1306]
## Expected behavior
@epalto can you confirm that timestamps within `.mat` are actually floats and e.g. `100.25` is a valid time stamp? the worst case is a diff of 1 second (`t_start = 100.25, t_end = 102.75` → `t_start = 100, t_end = 102`; does this diff matter? @aguirre-lab/ml4c3-dev 

## Possible solution
for correctness sake, I'll probably reindex everything but I don't think that should really interfere with #1265 
1. change column type in database
2. invalidate index (will keep current around)
3. reindex (3 day runtime)

**Comment by epalto** [comment]
Yes, waveforms on Bedmaster have a timestamp every 0.25 seconds, so timestamps are stored as floats. 1 second of data can be up to 240 points because a lot of ECGs are sampled at 240Hz but I don't think that really matters for most applications.

**Comment by StevenSong** [comment]
closing this because not big enough of an issue
