### ISSUE TITLE
Generate "table one" of demographics and other features

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1325]
## Question or modeling task
Use https://github.com/tompollard/tableone on `tensors_union.csv` from `explore`.

**Comment by erikr** [comment]
@StevenSong do you have bandwidth this week to help me with this?

**Comment by StevenSong** [comment]
some progress on this:

|                                     |        | Missing   | Overall       | 0.0           | 1.0          |
|-------------------------------------|--------|-----------|---------------|---------------|--------------|
| n                                   |        |           | 12682         | 12337         | 345          |
| ecg, mean (SD)                      |        | 0         | -1.9 (23.4)   | -2.0 (22.9)   | 0.4 (36.3)   |
| age, mean (SD)                      |        | 0         | 63.4 (15.2)   | 63.3 (15.1)   | 68.0 (15.4)  |
| sex, n (%)                          | female | 0         | 3961 (31.2)   | 3799 (30.8)   | 162 (47.0)   |
|                                     | male   |           | 8721 (68.8)   | 8538 (69.2)   | 183 (53.0)   |
| heart rate, mean (SD)               |        | 0         | 69.5 (15.3)   | 69.2 (15.1)   | 78.6 (18.7)  |
| pr, mean (SD)                       |        | 0         | 174.1 (34.6)  | 174.0 (34.5)  | 176.4 (38.3) |
| qt, mean (SD)                       |        | 0         | 410.9 (42.2)  | 411.0 (41.5)  | 406.8 (60.1) |
| qrs, mean (SD)                      |        | 0         | 100.7 (23.0)  | 100.6 (22.7)  | 106.6 (29.7) |
| raxis, mean (SD)                    |        | 0         | 16.4 (47.6)   | 16.1 (46.8)   | 26.9 (69.2)  |
| paxis, mean (SD)                    |        | 0         | 46.2 (26.7)   | 46.0 (26.4)   | 53.7 (34.8)  |
| taxis, mean (SD)                    |        | 0         | 54.8 (58.2)   | 54.3 (57.8)   | 73.9 (67.3)  |
| normal sinus rhythm, n (%)          | 0.0    | 0         | 395 (3.1)     | 389 (3.2)     | 6 (1.7)      |
|                                     | 1.0    |           | 12287 (96.9)  | 11948 (96.8)  | 339 (98.3)   |
| atrial fibrillation, n (%)          | 0.0    | 0         | 12577 (99.2)  | 12239 (99.2)  | 338 (98.0)   |
|                                     | 1.0    |           | 105 (0.8)     | 98 (0.8)      | 7 (2.0)      |
| atrial flutter, n (%)               | 0.0    | 0         | 12659 (99.8)  | 12316 (99.8)  | 343 (99.4)   |
|                                     | 1.0    |           | 23 (0.2)      | 21 (0.2)      | 2 (0.6)      |
| ischemia, n (%)                     | 0.0    | 0         | 10633 (83.8)  | 10364 (84.0)  | 269 (78.0)   |
|                                     | 1.0    |           | 2049 (16.2)   | 1973 (16.0)   | 76 (22.0)    |
| myocardial infarction, n (%)        | 0.0    | 0         | 9412 (74.2)   | 9182 (74.4)   | 230 (66.7)   |
|                                     | 1.0    |           | 3270 (25.8)   | 3155 (25.6)   | 115 (33.3)   |
| right atrial enlargement, n (%)     | 0.0    | 0         | 12537 (98.9)  | 12202 (98.9)  | 335 (97.1)   |
|                                     | 1.0    |           | 145 (1.1)     | 135 (1.1)     | 10 (2.9)     |
| left atrial enlargement, n (%)      | 0.0    | 0         | 10315 (81.3)  | 10047 (81.4)  | 268 (77.7)   |
|                                     | 1.0    |           | 2367 (18.7)   | 2290 (18.6)   | 77 (22.3)    |
| left ventricular hypertrophy, n (%) | 0.0    | 0         | 11569 (91.2)  | 11244 (91.1)  | 325 (94.2)   |
|                                     | 1.0    |           | 1113 (8.8)    | 1093 (8.9)    | 20 (5.8)     |
| left bundle branch block, n (%)     | 0.0    | 0         | 10442 (82.3)  | 10181 (82.5)  | 261 (75.7)   |
|                                     | 1.0    |           | 2240 (17.7)   | 2156 (17.5)   | 84 (24.3)    |
| right bundle branch block, n (%)    | 0.0    | 0         | 10439 (82.3)  | 10178 (82.5)  | 261 (75.7)   |
|                                     | 1.0    |           | 2243 (17.7)   | 2159 (17.5)   | 84 (24.3)    |
| pacemaker, n (%)                    | 0.0    | 0         | 12507 (98.6)  | 12171 (98.7)  | 336 (97.4)   |
|                                     | 1.0    |           | 175 (1.4)     | 166 (1.3)     | 9 (2.6)      |
| atrial paced rhythm, n (%)          | 0.0    | 0         | 12658 (99.8)  | 12314 (99.8)  | 344 (99.7)   |
|                                     | 1.0    |           | 24 (0.2)      | 23 (0.2)      | 1 (0.3)      |
| supraventricular tachycardia, n (%) | 0.0    | 0         | 12664 (99.9)  | 12320 (99.9)  | 344 (99.7)   |
|                                     | 1.0    |           | 18 (0.1)      | 17 (0.1)      | 1 (0.3)      |
| ectopic atrial rhythm, n (%)        | 0.0    | 0         | 12509 (98.6)  | 12173 (98.7)  | 336 (97.4)   |
|                                     | 1.0    |           | 173 (1.4)     | 164 (1.3)     | 9 (2.6)      |
| pericarditis, n (%)                 | 0.0    | 0         | 12646 (99.7)  | 12302 (99.7)  | 344 (99.7)   |
|                                     | 1.0    |           | 36 (0.3)      | 35 (0.3)      | 1 (0.3)      |
| st abnormality, n (%)               | 0.0    | 0         | 9058 (71.4)   | 8802 (71.3)   | 256 (74.2)   |
|                                     | 1.0    |           | 3624 (28.6)   | 3535 (28.7)   | 89 (25.8)    |
| t wave abnormality, n (%)           | 0.0    | 0         | 7258 (57.2)   | 7045 (57.1)   | 213 (61.7)   |
|                                     | 1.0    |           | 5424 (42.8)   | 5292 (42.9)   | 132 (38.3)   |
| av dissociation, n (%)              | 0.0    | 0         | 12679 (100.0) | 12334 (100.0) | 345 (100.0)  |
|                                     | 1.0    |           | 3 (0.0)       | 3 (0.0)       |              |
| ectopy, n (%)                       | 0.0    | 0         | 12676 (100.0) | 12331 (100.0) | 345 (100.0)  |
|                                     | 1.0    |           | 6 (0.0)       | 6 (0.0)       |              |
| uninterpretable ecg, n (%)          | 0.0    | 0         | 12682 (100.0) | 12337 (100.0) | 345 (100.0)  |
| mortality, n (%)                    | 0.0    | 0         | 12337 (97.3)  | 12337 (100.0) |              |
|                                     | 1.0    |           | 345 (2.7)     |               | 345 (100.0)  |
| stroke, n (%)                       | 0.0    | 0         | 12423 (98.0)  | 12124 (98.3)  | 299 (86.7)   |
|                                     | 1.0    |           | 259 (2.0)     | 213 (1.7)     | 46 (13.3)    |
| renal failure, n (%)                | 0.0    | 0         | 12233 (96.5)  | 12055 (97.7)  | 178 (51.6)   |
|                                     | 1.0    |           | 449 (3.5)     | 282 (2.3)     | 167 (48.4)   |
| prolonged ventilation, n (%)        | 0.0    | 0         | 11448 (90.3)  | 11353 (92.0)  | 95 (27.5)    |
|                                     | 1.0    |           | 1234 (9.7)    | 984 (8.0)     | 250 (72.5)   |
| dsw infection, n (%)                | 0.0    | 0         | 12653 (99.8)  | 12310 (99.8)  | 343 (99.4)   |
|                                     | 1.0    |           | 29 (0.2)      | 27 (0.2)      | 2 (0.6)      |
| reoperation, n (%)                  | 0.0    | 0         | 6254 (49.3)   | 6217 (50.4)   | 37 (10.7)    |
|                                     | 1.0    |           | 6428 (50.7)   | 6120 (49.6)   | 308 (89.3)   |
| long stay, n (%)                    | 0.0    | 0         | 11577 (91.3)  | 11333 (91.9)  | 244 (70.7)   |
|                                     | 1.0    |           | 1105 (8.7)    | 1004 (8.1)    | 101 (29.3)   |

**Comment by erikr** [comment]
Steven, great work!

Out of an abundance of caution, since this is unpublished, should we delete the above table and keep in our MGH Dropbox?

Do we have statistical significance tests comparing these counts or means for lived vs died?

**Comment by StevenSong** [comment]
deleted the above comment, todo:
- [ ] format table a bit (get rid of redundant rows/columns)
- [ ] move to dropbox
- [ ] t-test for lived vs died

**Comment by erikr** [comment]
`TableOne` has support for that t-test, yes?

**Comment by StevenSong** [comment]
> Does `TableOne` have support for that t-test?

no, but to be honest, the table isn't that complex, can probably manually generate

**Comment by erikr** [comment]
The repo suggests it does some statistical tests: https://github.com/tompollard/tableone#overview.

Just trying to find ways of saving you time :)

**Comment by StevenSong** [comment]
ah, thx, it shows how to obtain in the google collab notebook

**Comment by StevenSong** [comment]
at `dropbox/sts-ecg/figures-and-tables/table-one.csv`
