### ISSUE TITLE
Fix `learning_rate_schedule`

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1338]
## Error message or warning
- `learning_rate_schedule` is not compatible with ReduceLRonPlateau
- `steps_per_epoch` is None in `_get_learning_rate_schedule`

## Steps to reproduce
1.
2.
3.
4.

**Comment by erikr** [comment]
Closing; redundant w/ https://github.com/aguirre-lab/ml4c3/issues/1333
