### ISSUE TITLE
Tensorize EDW and Bedmaster data: CABG cohort

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#761]
## Assigned IDs
- [x] @RogerPallares: Create `xref_cabg.csv`
- [ ] @RogerPallares (Olympus): first 0, last 500
- [ ] @raimonpv (Montserrat): first 500, last 1000
- [ ] @epalto (Everest): first 1000, last 1500
- [ ] @erikr (Mithril): first 1500, last 2000
- [ ] @StevenSong (Anduril): first 2000, last 2641

## Syntax
```bash
./scripts/run.sh $PWD/ml4c3/recipes.py tensorize_icu_no_edw_pull \
--num_workers 10 \
--adt /media/ml4c3/cohorts_lists/adt_cabg.csv \
--xref /media/ml4c3/cohorts_lists/xref_cabg.csv \
--alarms /media/ml4c3/bedmaster_alarms \
--mrn_start_index 1000 \
--mrn_end_index 1500 \
--tensors /media/ml4c3/hd5_cabg_$YOUR_INITIALS \
--staging_dir ~/icu-temp \
--staging_batch_size 10 \
--allow_one_source \
--overwrite
```

## Context
Need to retensorize data because of bedmaster data sorting bug; see https://github.com/aguirre-lab/ml4c3/pull/758#issuecomment-723342744 and https://github.com/aguirre-lab/ml4c3/issues/748

## Acceptance Criteria
`hd5` files are in `/media/mad3/hd5`

## Blocked by
~https://github.com/aguirre-lab/ml4c3/issues/748~
~https://github.com/aguirre-lab/ml4c3/issues/773~
~https://github.com/aguirre-lab/ml4c3/issues/853~
~https://github.com/aguirre-lab/ml4c3/issues/967~
~https://github.com/aguirre-lab/ml4c3/issues/1053~
https://github.com/aguirre-lab/ml4c3/issues/1137
#1142

**Comment by erikr** [comment]
@RogerPallares, can you please remind me what would differ between a) our current `hd5` files on `mad3` and b) the new data that would be retensorized (as described in this issue)?

**Comment by RogerPallares** [comment]
> @RogerPallares, can you please remind me what would differ between a) our current `hd5` files on `mad3` and b) the new data that would be retensorized (as described in this issue)?

Yes, of course. We are retensoziring because: 1) a bedmaster data sorting bug (see #758 (comment) and #748), as described in this issue (section "context"); and 2) Now the ADT table contains all CSNs of the desired patients, not only the ones related to the desired intervention/event (cabg, rapid response, etc.)

**Comment by erikr** [comment]
I see, thanks for reminding me!

**Comment by erikr** [comment]
I updated the syntax in the issue body to reflect our updated argument names:
```
--mrn_start_index 0 \
--mrn_end_index 999 \
```

**Comment by erikr** [comment]
Tensorized 173G of HD5 files for MRN indices 1501-2000, but encountered an error: https://github.com/aguirre-lab/ml4c3/issues/1137.

@RogerPallares, if I re-run the syntax with `--overwrite`, will tensorization restart from MRN index 0? How do you suggest I try again without wasting all of the already tensorized data?

**Comment by RogerPallares** [comment]
> Tensorized 173G of HD5 files for MRN indices 1501-2000, but encountered an error: #1137.
> 
> @RogerPallares, if I re-run the syntax with `--overwrite`, will tensorization restart from MRN index 0? How do you suggest I try again without wasting all of the already tensorized data?

Some time ago @raimonpv  developed a small script that removes the unfinished HD5 files (this is the script https://github.com/aguirre-lab/ml4c3/blob/master/scripts/remove_unfinished_icu_hd5.py), and then the pipeline can be re-run without `--overwrite`, which will only tensorize the remaining files. I'll also take a look at the issue!

**Comment by erikr** [comment]
@RogerPallares thanks for pointing out that helpful script. I successfully ran it.

**Comment by erikr** [comment]
Closing issue. Outdated and we will start fresh on a hybrid cohort (union between arrests and CABG).
