### ISSUE TITLE
Create introductory notebook to onboard users to ml4c3

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#848]
## Why it Matters

We need to provide new users (e.g. Stultz Lab) with a clear and simple introduction to Docker-based workflow for accessing ECGs.

Unfortunately users who work with our ECGs are still trying to spin up their own environments and code bases, which is not optimal given all of the effort we've put into `ml4c3` and its useful capabilities.

It means they reinvent the wheel. Moreover, work outside of our repo will never be incorporated here and usable by others now and in the future.

Perhaps a cleaner onboarding experience will at least encourage people to use our Docker environment.

## Possible Solution
Create a notebook that acquaints a user with tensor maps, how our ECGs are structured, etc. and culminates in the extraction of ECG voltage as a numpy array and plots it. Would be cool to use code in `plots.py` for the latter.

## Acceptance Criteria
New intro to ecg NB

**Comment by erikr** [comment]
@StevenSong should the docs or README link to this notebook?

**Comment by StevenSong** [comment]
> @StevenSong should the docs or README link to this notebook?

yes also thoughts on hosting on google collab so that its runnable? i wonder how we'd get our code there though, maybe more trouble than its worth

**Comment by erikr** [comment]
Google CoLab would be seamless and lower barrier to entry. But it seems it won't work.

We can clone a repo https://stackoverflow.com/questions/48350226/methods-for-using-git-with-google-colab

or load directly from GitHub ![Screen Shot 2021-01-26 at 10 36 38 AM](https://user-images.githubusercontent.com/1253422/105866801-5fc56c00-5fc2-11eb-8dfb-837840ff6612.png)

**but** no docker support, now or ever https://github.com/googlecolab/colabtools/issues/299#issuecomment-615308778.
👎🏼
