### ISSUE TITLE
Tensorize new data in existing HD5

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#941]

**Comment by erikr** [comment]
@RogerPallares is this the default behavior, and disabled if the user sets
https://github.com/aguirre-lab/ml4c3/blob/61d35cac94c3b21ece90d0fc350ef1bf21b35cc9/ml4c3/arguments.py#L290-L294

**Comment by raimonpv** [comment]
New data is not tensorized in the files. The `overwrite` argument will just tensorize again all the MRNs from scratch. If it is not set (default) it will skip the MRNs that already exist in the tensors directory.

I think that from the Bedmaster tensorization, we don't have to be in charge of this. From the EDW side, the tensorization is fast enough to not have to worry about that yet, as I don't think is a problem to tensorize again some patients. (In less than one day I've tensorized all the EDW data for ~4200 arrest CSNs). We might want to implement that if at some point we want to add a new type of EDW data and we already have thousands of tensorized data.

**Comment by erikr** [comment]
Thanks, sounds good to:
1. Not implement any new features for Bedmaster tensorization. This can be a feature request to @matt-cdac @contactadityag.
2. Regarding EDW, we may want to tensorize in an "update" mode, but we can revisit if there is a need. For now, I'll close this issue.
