### ISSUE TITLE
If EDW data already exists at destination, log the destination

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#994]

**Comment by raimonpv** [comment]
Could you be more specific on the goal of this issue?
Right now the pipeline loggs this message if a MRN/CSN is already at destination:
https://github.com/aguirre-lab/ml4c3/blob/master/ingest/edw/pipeline.py#L261-L263
```
                f"MRN: {row.MRN} ({index + 1}/{patients.shape[0]}), CSN: "
                f"{row.PatientEncounterID} already exists at destination; "
                "skipping.",
```
What you propose is to add into this message the exact path to the folder?

**Comment by erikr** [comment]
This is from so long ago that I do not remember the details 😆 

I think this is already implemented, as you point out. I'll close it. Thanks!
